version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: angular-app

    # env_file:
    #     - ".env"
      
    ports:
      - 4200:4200
    # volumes:
    #   - "./app/:/app"
    
    # depends_on:
    #   - "redis"
    #   - "db_postgres"
      
    # networks:
    #   - angular_default

    # command: > 
    #     bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

# networks:
#   elpis_default:
#     external: true
#     name: angular_default

volumes:
  redis: {}
  
